2024-02-03 15:50:33,164 INFO    MainThread:4014703 [wandb_setup.py:_flush():76] Current SDK version is 0.16.2
2024-02-03 15:50:33,164 INFO    MainThread:4014703 [wandb_setup.py:_flush():76] Configure stats pid to 4014703
2024-02-03 15:50:33,164 INFO    MainThread:4014703 [wandb_setup.py:_flush():76] Loading settings from /home/syncthreads/.config/wandb/settings
2024-02-03 15:50:33,164 INFO    MainThread:4014703 [wandb_setup.py:_flush():76] Loading settings from /home/syncthreads/mikey/madrona_escape_room_pixact/wandb/settings
2024-02-03 15:50:33,164 INFO    MainThread:4014703 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-03 15:50:33,164 INFO    MainThread:4014703 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-03 15:50:33,164 INFO    MainThread:4014703 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'scripts/train.py', 'program_abspath': '/home/syncthreads/mikey/madrona_escape_room_pixact/scripts/train.py', 'program': '/home/syncthreads/mikey/madrona_escape_room_pixact/scripts/train.py'}
2024-02-03 15:50:33,164 INFO    MainThread:4014703 [wandb_init.py:_log_setup():526] Logging user logs to /home/syncthreads/mikey/madrona_escape_room_pixact/wandb/run-20240203_155033-0jhyodon/logs/debug.log
2024-02-03 15:50:33,164 INFO    MainThread:4014703 [wandb_init.py:_log_setup():527] Logging internal logs to /home/syncthreads/mikey/madrona_escape_room_pixact/wandb/run-20240203_155033-0jhyodon/logs/debug-internal.log
2024-02-03 15:50:33,164 INFO    MainThread:4014703 [wandb_init.py:init():566] calling init triggers
2024-02-03 15:50:33,164 INFO    MainThread:4014703 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'gpu_id': 0, 'ckpt_dir': 'build/ckpts-debug', 'restore': None, 'num_worlds': 1, 'num_updates': 10, 'steps_per_update': 40, 'num_bptt_chunks': 8, 'lr': 0.0001, 'gamma': 0.998, 'entropy_loss_coef': 0.01, 'value_loss_coef': 0.5, 'clip_value_loss': False, 'num_channels': 256, 'separate_value': False, 'fp16': True, 'gpu_sim': False, 'profile_report': True, 'rawPixels': True, 'cpu': False}
2024-02-03 15:50:33,164 INFO    MainThread:4014703 [wandb_init.py:init():616] starting backend
2024-02-03 15:50:33,164 INFO    MainThread:4014703 [wandb_init.py:init():620] setting up manager
2024-02-03 15:50:33,165 INFO    MainThread:4014703 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-02-03 15:50:33,165 INFO    MainThread:4014703 [wandb_init.py:init():628] backend started and connected
2024-02-03 15:50:33,166 INFO    MainThread:4014703 [wandb_init.py:init():720] updated telemetry
2024-02-03 15:50:33,170 INFO    MainThread:4014703 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-03 15:50:33,439 INFO    MainThread:4014703 [wandb_run.py:_on_init():2254] communicating current version
2024-02-03 15:50:33,521 INFO    MainThread:4014703 [wandb_run.py:_on_init():2263] got version response 
2024-02-03 15:50:33,521 INFO    MainThread:4014703 [wandb_init.py:init():804] starting run threads in backend
2024-02-03 15:50:33,558 INFO    MainThread:4014703 [wandb_run.py:_console_start():2233] atexit reg
2024-02-03 15:50:33,558 INFO    MainThread:4014703 [wandb_run.py:_redirect():2088] redirect: wrap_raw
2024-02-03 15:50:33,558 INFO    MainThread:4014703 [wandb_run.py:_redirect():2153] Wrapping output streams.
2024-02-03 15:50:33,558 INFO    MainThread:4014703 [wandb_run.py:_redirect():2178] Redirects installed.
2024-02-03 15:50:33,558 INFO    MainThread:4014703 [wandb_init.py:init():847] run started, returning control to user process
2024-02-03 15:50:35,786 ERROR   MainThread:4014703 [util.py:get_module():267] Error importing optional module moviepy.editor
Traceback (most recent call last):
  File "/home/syncthreads/mikey/mikey_env/lib/python3.11/site-packages/wandb/util.py", line 233, in import_module_lazy
    return sys.modules[name]
           ~~~~~~~~~~~^^^^^^
KeyError: 'moviepy.editor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/syncthreads/mikey/mikey_env/lib/python3.11/site-packages/wandb/util.py", line 262, in get_module
    return import_module_lazy(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syncthreads/mikey/mikey_env/lib/python3.11/site-packages/wandb/util.py", line 235, in import_module_lazy
    spec = importlib.util.find_spec(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib.util>", line 94, in find_spec
ModuleNotFoundError: No module named 'moviepy'
